# Generated by Django 4.0 on 2021-12-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_two',
            field=models.TextField(blank=True),
        ),
    ]
